[package]
name = "ruby_parser"
version = "0.1.0"
authors = ["Charlie Somerville <charlie@charlie.bz>"]
build = "build.rs"
include = [
    "build.rs",
    "Cargo.toml",
    "cc/capi.cc",
    "cc/driver.cc",
    "cc/grammars/typedruby24.ypp",
    "cc/literal.cc",
    "cc/lexer.rl",
    "cc/state_stack.cc",
    "cc/token.cc",
    "codegen/builder.rb",
    "codegen/diagnostics.rb",
    "include/optional.hh",
    "include/ruby_parser/builder.hh",
    "include/ruby_parser/capi.hh",
    "include/ruby_parser/diagnostic.hh",
    "include/ruby_parser/diagnostic_class.hh",
    "include/ruby_parser/driver.hh",
    "include/ruby_parser/lexer.hh",
    "include/ruby_parser/literal.hh",
    "include/ruby_parser/node.hh",
    "include/ruby_parser/pool.hh",
    "include/ruby_parser/state_stack.hh",
    "include/ruby_parser/token.hh",
    "src/ast.rs",
    "src/builder.rs",
    "src/ffi.rs",
    "src/lib.rs",
    "src/parser.rs",
    "src/sexp.rs",
]

[dependencies]
libc = "0.2.0"
onig = { version = "1.2", optional = true }

[build-dependencies]
cc = "1.0"

[features]
default = []
regex = ["onig"]

[dev-dependencies]
glob = "0.2"
difference = "1.0"

[profile.dev]
debug = true
panic = "abort"
